### ISSUE TITLE
Updating a contact does not work

### ISSUE THREAD

**Issue by andyneil** [umbraco/Umbraco.Forms.Integrations#17]
If you use the `HubspotWorkflow` workflow more than once with the same details, it will fail.
After checking the source, this looks to be because the response returned from HS is HTTP 409 - Conflict.
Should the functionality be extended to:
- First check if the contact exists in HS, if so get the contactId
-- If so, make a subsequent PATCH call, to /crm/v3/objects/contacts/{contactId} as detailed in the [API docs](https://developers.hubspot.com/docs/api/crm/contacts)
-- If not, continue the create as currently works.

**Comment by AndyButland** [comment]
We've applied an update to do an update if the contact already exists according to HubSpot via a provision of a 409 response.
