### ISSUE TITLE
Multi target for 8, 9 and 10

### ISSUE THREAD

**Issue by hifi-phil** [umbraco/Umbraco.Forms.Integrations#20]
We are using this package in one of our solutions and we are updating to 9. Is there a 9 version available or would you like us to multi target this one?

**Comment by AndyButland** [comment]
Hi @hifi-phil - I'm afraid we haven't yet got around to updating this one to support Umbraco 9, but as you may have seen, we've adopted the multi-targeting approach for the other small integration projects we've built over the past months.  So yes, we'd suggest and would expect to do the same for this one.

As I say though, we haven't got to it yet, so if you had a need for this on Umbraco 9 and were minded to do it and submit it as a PR, we'd certainly appreciate it and arrange an updated release.  Thanks very much if so. // @acoumb.

**Comment by hifi-phil** [comment]
Hi @AndyButland, should be able to take a look this week. Is there a style you would like me to follow, maybe point me to another repo?

**Comment by AndyButland** [comment]
There's an example in this repo, if you see the Zapier integration found [here](https://github.com/umbraco/Umbraco.Forms.Integrations/tree/main/src/Umbraco.Forms.Integrations.Automation.Zapier).

Would suggest it's also worth a read of [this blog post](https://umbraco.com/blog/multi-targeted-package-migration/), and the video embedded within, to get an idea of how we've used the multi-targeting approach to support Umbraco 8 and 9 in the same project.

**Comment by acoumb** [comment]
Hi @hifi-phil , we have also prepared new versions of [Hubspot](https://github.com/umbraco/Umbraco.Forms.Integrations/tree/main-v10/src/Umbraco.Forms.Integrations.Crm.Hubspot) and [Zapier](https://github.com/umbraco/Umbraco.Forms.Integrations/tree/main-v10/src/Umbraco.Forms.Integrations.Automation.Zapier) , you can check those also for reference.
I will close this now, but feel free to reach out if you have other questions.
