### ISSUE TITLE
Send forms to hubspot

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Forms.Integrations#3]
We love Umbraco and we love Hubspot so great news you are looking into the integration.

We have been thinking about the integration to and we've come to the conclusion that with all our clients there is a clear separation between marketeers/sales and content editors. The marketeers/sales stay in Hubspot  and content editors stay in Umbraco.
Yes in smaller companies there is overlap between marketeers and content editors but sales want their leads including all communication in Hubspot.

If we only submit the contact to Hubspot  we mis the complete communication with that contact in Hubspot  and force the sales person to login into Umbraco and manually copy the content to Hubspot

The way we integrate with Hubspot is via a form picker (custom datatype). A content editor picks a Hubspot form to be rendered on a page and we use the embed code of Hubspot combined with the form id from the form picker.
The same can be done with CTA's in Hubspot for example.

This means we replace forms with Hubspot  integration. This is probably not the goal of Umbraco but I don't think customers that use the forms in Hubspot would use Umbraco forms and instead would use some custom integration like we do.

Is there a option to move this integration away from being a forms addon and instead being a Umbraco addon?
If so we are willing and able to actively help with the integration. We don't have to stop with forms but can continue with CTA and whatever is a logical addition.

I'm looking forward to your opinion @AndyButland 

Kind regards, 
Frans

**Comment by AndyButland** [comment]
Thanks Frans - I had a similar chat with Ronald on this who had also seen this setup.  It does make sense if you are more embedded with using HubSpot, and the integration we've provided here is probably more if you are already invested in Umbraco Forms and want a quick way to "also send the data to HubSpot".  

Your suggestion sounds a good idea, but it'll be a second, new integration if we were to go ahead with it, so outside of the scope of this one (as of course with the alternative approach, there's not a role for Umbraco Forms).

**Comment by AndyButland** [comment]
Closing as this feature is now handled by the [additional package with CMS integration](https://our.umbraco.com/packages/website-utilities/hubspot-umbraco-cms-integration/).
