### ISSUE TITLE
Hubspot v2.0.1 authentication issue

### ISSUE THREAD

**Issue by Sven883** [umbraco/Umbraco.Forms.Integrations#56]
Hello!

We're using hubspot v2.0.1 on a umbraco v8.14.1.
We've noticed some issue with the authentication using hubspot in umbraco forms.

When we add a 'save contact to hubspot' workflow and click 'authorize' we get the following messages in the backoffice:
![image](https://user-images.githubusercontent.com/77729251/201946377-9ec24d75-0dc1-4655-ba30-572be09cb943.png)

Our hubspot fields are loaded but hubspot is not connected.
Umbraco backoffice errors when submitting the form:

`Could not retrieve authenticate with HubSpot API. Status code: BadRequest, reason: Bad Request, content: {"status":"BAD_AUTH_CODE","message":"missing or unknown auth code","correlationId":"f995a19e-5f2c-4a6a-88ce-446555b8ae94"}`

`Error updating a HubSpot contact.`

`Error creating a HubSpot contact.`

Any idea how to fix this?
Also - I've noticed that there is a hubspot v2.0.2. Are there any important changes?

Thanks in advance!

**Comment by Sven883** [comment]
Hello @acoumb, I noticed that you self-assigned this issue.
Have you found anything? 
Thanks!

**Comment by acoumb** [comment]
Hi @Sven883 , I hope to get a chance to look at it today. I will keep you posted with any updates.

**Comment by Sven883** [comment]
@acoumb, ok thanks!

**Comment by acoumb** [comment]
Hello again @Sven883 . 
i have fixed the issue reported, until the package gets released could you use the commit sample [here](https://github.com/umbraco/Umbraco.Forms.Integrations/pull/57/commits/d1f70669487a90cd4c9f981eaf101332216518b5) to test if it’s fixed?
Thank you

**Comment by Sven883** [comment]
@acoumb I've tested this, and so far so good!
We can successfully create and update contacts in hubspot via umbraco forms integration!

**Comment by Sven883** [comment]
@acoumb when will there be a new package version?

**Comment by acoumb** [comment]
today probably, latest tomorrow morning.

**Comment by Sven883** [comment]
@acoumb , ok thanks for info!

**Comment by acoumb** [comment]
@Sven883 the [package](https://www.nuget.org/packages/Umbraco.Forms.Integrations.Crm.Hubspot/2.0.3) is out.

I am closing this now, feel free to reach out if you have other questions.

**Comment by acoumb** [comment]
Both versions for Umbraco 8, 9 and for Umbraco 10 are out.

**Comment by Sven883** [comment]
@acoumb we've installed the latests version for umbraco 8 on our live environment and we notice that we still get this error:
'Error creating a HubSpot contact.'
Testing was done by manually changing the app_plugin code with the code you provided.
Live was done by upgrading to the latest release of the package.
Any idea whats wrong?

**Comment by acoumb** [comment]
Hi, I will run some tests and get back to you. Do you get other details in the logs? Is it a new contact, or update on an existing one?
Thank you

**Comment by Sven883** [comment]
@acoumb, error from trying to create a hubspot contact.
information log about:
`Contact already exists in HubSpot CRM and workflow is configured to not apply updates, so update of information was skipped.`

**Comment by Sven883** [comment]
this is our field mapping:
![image](https://user-images.githubusercontent.com/77729251/203495388-a0d8616f-de1e-4070-b2f5-621cab9d3222.png)

**Comment by acoumb** [comment]
This is because with version [2.0.2](https://our.umbraco.com/packages/developer-tools/hubspot-umbraco-forms-integration/) we've introduced the option to disable contact update by default, so that a contact cannot be updated by anyone who might know the email address. 
If you add [this](https://github.com/umbraco/Umbraco.Forms.Integrations/blob/main/src/Umbraco.Forms.Integrations.Crm.Hubspot/Configuration/HubspotSettings.cs) setting with `true` value, it should be ok.

**Comment by Sven883** [comment]
@acoumb do we add this key with value = true to our web.config?
Umbraco.Forms.Integrations.Crm.Hubspot.AllowContactUpdate

**Comment by acoumb** [comment]
Correct

**Comment by Sven883** [comment]
@acoumb any update on the 'error creating hubspot contact' with v2.0.3?

**Comment by acoumb** [comment]
I've tried replicating the issue locally and on a Cloud test site, and did not experience any issues. I've recorded the Cloud test run [here](https://drive.google.com/file/d/1okdZcaoe3HPozFO9M3c3NAbV_qm9LgZ3/view?usp=share_link) , the test site is running 8.18.5 and version 2.0.3 of the HubSpot package. If you notice anything out of the ordinary or want me to send you an invitation so you can test on the test site, just let me know.

**Comment by Sven883** [comment]
@acoumb we're running an umbraco v8.14.1 - Maybe that's the issue?

**Comment by acoumb** [comment]
Don’t think so, might be something HubSpot specific.

**Comment by acoumb** [comment]
I would presume it's a HubSpot specific error, would you care testing your HubSpot account with the cloud test site I am using in the recorded video?

**Comment by acoumb** [comment]
Hi @Sven883 , have you made any progress regarding the HubSpot error? Would you like to try it out with my cloud test site to see if it works?

**Comment by Sven883** [comment]
Hey @acoumb, I've found the error by debugging the code + using the endpoint tests (https://developers.hubspot.com/docs/api/crm/contacts#endpoint?spec=PATCH-/crm/v3/objects/contacts/{contactId})
I noticed that we were trying to send the wrong data to a field hr_language.
We didn't receive any information about that in the logs using this hubspot package.
I did get the information using the developers docs endpoint test.

**Comment by acoumb** [comment]
Hi @Sven883 , in this case can we close now this issue?

**Comment by Sven883** [comment]
Hey @acoumb, yes! I'll close this issue.
Thanks for helping out!
