### ISSUE TITLE
Issue with Zappier integration

### ISSUE THREAD

**Issue by andyfelton-equatedigital** [umbraco/Umbraco.Forms.Integrations#64]
Hi,

I'm trying to use the Zappier integration against our website and am getting the error:
![image](https://user-images.githubusercontent.com/96947768/214366998-5c9e4235-2430-4acd-95ac-08843256ea7a.png)

I've tried the same request within PostMan and got what looks like a valid response - not sure how to debug this can you provide any help so I can proceed?

Thanks
Andy

**Comment by acoumb** [comment]
Hi @andyfelton-equatedigital ,

I am looking into the issue, in the meantime, could you provide me some details?
- Umbraco version
- Zapier package version
- You are able to authenticate, but the error occurs when retrieving the forms?

Thank you

**Comment by andyfelton-equatedigital** [comment]
Hi @acoumb 

Sorry you're quite correct the information I provided was poor - yes authenticated without issue then failed to retrieve forms - btw using the username and password validation.

Umbraco.Cms - 11.0.0
Umbraco.Cms.Integrations.Automation.Zapier - 1.1.1
Umbraco.Forms.Integrations.Automation.Zapier - 2.0.4
Umbraco.Forms - 11.0.0

Thanks
Andy

**Comment by acoumb** [comment]
Hi, 

As I haven't managed to replicate it yet, could you make a quick test for me using an HTTP client like Postman or VS Code?

Could you make a GET request to this endpoint: `[your_site_base_url]/umbraco/api/form/getforms` and add the following two header pairs:
- `X-USERNAME` = user email
- `X-PASSWORD` = user password

And then could you send me the results?

Thank you.

**Comment by andyfelton-equatedigital** [comment]
Hi,

I've attached the information as requested.

Thanks
Andy

[forms.txt](https://github.com/umbraco/Umbraco.Forms.Integrations/files/10512730/forms.txt)

**Comment by andyfelton-equatedigital** [comment]
@acoumb Just wondered if you got anywhere with this one?

**Comment by acoumb** [comment]
Hi,

I was away, but I will resume testing tomorrow.

**Comment by acoumb** [comment]
Hi @andyfelton-equatedigital ,

I've set up this morning a sandbox environment in Azure with the configurations you have, but was unable to replicate the issue.
You can check it yourself here: https://umb11azuresandbox.azurewebsites.net/umbraco (aco@umbraco.com / 1K_5GvE4lY). I was able to authenticate and query the forms sucessfully.
![2023-01-31_10-32-12](https://user-images.githubusercontent.com/95346674/215709103-ff29cfb9-7b77-4c4e-8463-ddf332c3cbc9.png)
![2023-01-31_10-31-45](https://user-images.githubusercontent.com/95346674/215709121-0c94409a-3942-4cbf-8b44-1299a920507b.png)

Maybe you have other settings that might cause the issue?

Or maybe try the [code](https://github.com/umbraco/Umbraco.Forms.Integrations/blob/e64092b85a0d5f1b9975989b6da27d8d7bbf39e4/src/Umbraco.Forms.Integrations.Automation.Zapier/Controllers/FormController.cs#L33) block from the package that is retrieving the forms in a different environment.

Thanks,
Adrian

**Comment by andyfelton-equatedigital** [comment]
Hi @acoumb 

I've tried some more debug and am not making much progress. I can configure the site you sent in my Zappier, and all works fine. I've reduced the number of forms on my site and still no joy - are you able to provide a link to the code running in Zappier so I can debug more from that?

Also if you provide me with another way of providing information I can share the credentials of the site with you.

Thanks
Andy

**Comment by acoumb** [comment]
The code block for retrieving the forms: https://github.com/umbraco/Umbraco.Forms.Integrations/blob/main/src/Umbraco.Forms.Integrations.Automation.Zapier/Services/ZapierFormService.cs

If you run that into your solution, does it return values?

Could you also try with an API key?

You will need two settings:
-Umbraco:Cms:Integrations:Automation:Zapier:Settings:ApiKey
- Umbraco:Forms:Integrations:Automation:Zapier:Settings:ApiKey

**Comment by andyfelton-equatedigital** [comment]
@acoumb I was looking for the code which runs on the Zappier side to retrieve the forms.

**Comment by acoumb** [comment]
@andyfelton-equatedigital requests are made to this endpoint: `[base_url]/umbraco/api/form/getforms` and the following header keys are passed:
- `X-USERNAME` and `X-PASSWORD` if you use username/password pair for authentication
- `X-APIKEY` if you want to use an API key stored in the settings of the website.

**Comment by andyfelton-equatedigital** [comment]
@acoumb Hiya,

Sorted that now the URL appears to need to be entered without the trailing / unless it fails with a 404!

**Comment by acoumb** [comment]
Hi @andyfelton-equatedigital ,
I will take you input into consideration and see how can this be managed in the future.
Closing this for now, if you have other observations, please let us know.
Thank you.
