### ISSUE TITLE
Issue with Umbraco Forms

### ISSUE THREAD

**Issue by andyfelton-equatedigital** [umbraco/Umbraco.Forms.Integrations#81]
Hi,

I've hit an issue with the Zapier Integration and Umbraco Forms/Umbraco. Once the Zapier integration is installed with Umbraco 11.3.1 and Umbraco.Forms 11.1.2 (even if it's not configured) then no data is saved to the database after this.

Thanks
Andy

**Comment by andyfelton-equatedigital** [comment]
Pull request #82 was created to resolve the issue with missing scope.complete

**Comment by andyfelton-equatedigital** [comment]
Hi @acoumb,

Wondering when the next release of this would be planned so I can work out if to build and deploy locally or not.

Many Thanks
Andy

**Comment by acoumb** [comment]
Hi Andy,
I will review your PR and after merge, I can prepare a release for tomorrow, or Monday the latest.

Thanks,
Adrian

**Comment by andyfelton-equatedigital** [comment]
@acoumb Have you any updates on this?

**Comment by acoumb** [comment]
Hi, it will come out today.

**Comment by acoumb** [comment]
The new version [2.0.5](https://www.nuget.org/packages/Umbraco.Forms.Integrations.Automation.Zapier/2.0.5) has been released.

Thank you for your help with this!
