### ISSUE TITLE
Forms to Contacts not working

### ISSUE THREAD

**Issue by LawrenceWorks** [umbraco/Umbraco.Forms.Integrations#85]
We're using Umbraco Forms and the HubSpot CMS integration, but we're not receiving any of the contacts after form submissions. I’ve already authorised the workflow and connected it through our HubSpot account. I’ve also added in the field mappings, is there something we’re missing?

**Comment by EPDA-parky** [comment]
@LawrenceWorks could i have an update? Thanks

**Comment by acoumb** [comment]
Hi @LawrenceWorks , 

Could you tell me which versions of Umbraco/Forms/Hubspot you are using? I've tested against a version 10 with private access tokens and OAuth, and could not replicate the issue.

Thanks

**Comment by LawrenceWorks** [comment]
Hi guys,

Apologies for the late reply, in the end, I couldn't get it to work so I've just gone with creating a custom workflow and used their API documentation to hardcode the fields we need from our forms to Hubspot contacts.
