### ISSUE TITLE
Forms not integrating with Zapier

### ISSUE THREAD

**Issue by EPDA-parky** [umbraco/Umbraco.Forms.Integrations#86]
Hi I am trying to integrate Umbraco Form to CRM Copper using Zapier. 

But in Zapier I get the message: Unable to load choices
We're having trouble loading 'Form' data. The app returned "Server Error".

<img width="861" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Integrations/assets/92502473/fe4ea537-fbde-4dcb-83f4-0b6859f43d8f">

Thanks

**Comment by EPDA-parky** [comment]
Hello could we have an update on this please? Thanks @nul800sebastiaan

**Comment by EPDA-parky** [comment]
Hello could we have an update on this please? Thanks @warrenbuckley

**Comment by acoumb** [comment]
Hi @EPDA-parky ,

Following your reported issue I identified the problem and created a RC version of the package on `MyGet` before releasing it to `NuGet`. Could you please test it out by installing the CMS version `1.2.0-rc1` of the package using this package source `https://www.myget.org/F/umbracoprereleases/api/v3/index.json`, and make your Zaps use version 2.1.0 of the Umbraco Zapier App?

Please let me know how it goes.

Thank you,
Adrian

**Comment by EPDA-parky** [comment]
Hi Adrian

Thank you for getting back to me. To upgrade the CMS – how do I do that? Also is it advisable to do so on a Staging Site first? Or is the process much simple?

Many thanks

Duncan

From: Adrian Cojocariu ***@***.***>
Reply to: "umbraco/Umbraco.Forms.Integrations" ***@***.***>
Date: Wednesday, 12 July 2023 at 15:26
To: "umbraco/Umbraco.Forms.Integrations" ***@***.***>
Cc: Duncan Crossland ***@***.***>, Mention ***@***.***>
Subject: Re: [umbraco/Umbraco.Forms.Integrations] Forms not integrating with Zapier (Issue #86)


Hi @EPDA-parky<https://github.com/EPDA-parky> ,

Following your reported issue I identified the problem and created a RC version of the package on MyGet before releasing it to NuGet. Could you please test it out by installing the CMS version 1.2.0-rc1 of the package using this package source https://www.myget.org/F/umbracoprereleases/api/v3/index.json, and make your Zaps use version 2.1.0 of the Umbraco Zapier App?

Please let me know how it goes.

Thank you,
Adrian

**Comment by acoumb** [comment]
Hi,

You will need to update the Umbraco.Cms.Integrations.Automation.Zapier package to version 1.2.0-rc1. Since this is a RC version, a staging environment setup would be helpful.

Thanks,
Adrian

**Comment by EPDA-parky** [comment]
Hi No we were unable to use the new version as it was incompatible with our version of Umbraco.

How will I create an API in Umbraco for Zapier?

Many thanks

Duncan

From: Adrian Cojocariu ***@***.***>
Reply to: "umbraco/Umbraco.Forms.Integrations" ***@***.***>
Date: Wednesday, 19 July 2023 at 14:02
To: "umbraco/Umbraco.Forms.Integrations" ***@***.***>
Cc: Duncan Crossland ***@***.***>, Mention ***@***.***>
Subject: Re: [umbraco/Umbraco.Forms.Integrations] Forms not integrating with Zapier (Issue #86)


Hi @EPDA-parky<https://github.com/EPDA-parky> ,

Did you manage to test with the new version of the package?

Thanks

**Comment by acoumb** [comment]
Were you trying to use the package on Umbraco 7? Because it only support Umbraco 8+.

**Comment by EPDA-parky** [comment]
Yes we have Umbraco 7 – thanks.

D



From: Adrian Cojocariu ***@***.***>
Reply to: "umbraco/Umbraco.Forms.Integrations" ***@***.***>
Date: Thursday, 20 July 2023 at 08:09
To: "umbraco/Umbraco.Forms.Integrations" ***@***.***>
Cc: Duncan Crossland ***@***.***>, Mention ***@***.***>
Subject: Re: [umbraco/Umbraco.Forms.Integrations] Forms not integrating with Zapier (Issue #86)


Were you trying to use the package on Umbraco 7? Because it only support Umbraco 8+.

**Comment by acoumb** [comment]
Unfortunately, the package works for [8.4+](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Automation.Zapier).

Closing this for now.
Thank you
