### ISSUE TITLE
Umbraco Forms will not export data

### ISSUE THREAD

**Issue by EPDA-parky** [umbraco/Umbraco.Forms.Integrations#87]
Umbraco Forms will not export data

**Comment by AndyButland** [comment]
We'll need a bit more to go on than this @EPDA-parky please.  Assuming this is an issue with Umbraco Forms itself, please can you raise the issue on [this tracker](https://github.com/umbraco/Umbraco.Forms.Issues/issues) with some additional details? 

It's useful to know:

- What version you are running?
- Specifically what you are doing to trigger the issue?
- What might we need to replicate the issue?
- Are there any errors reported in the logs or browser console?

Thanks.

**Comment by EPDA-parky** [comment]
What version you are running?
7.15.10 

Specifically what you are doing to trigger the issue?
1. Clicking on Export
<img width="207" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Integrations/assets/92502473/316182e5-eb74-422f-a3b8-6db4c5e68773">

2. Selecting format
<img width="373" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Integrations/assets/92502473/87775eb2-8f1e-4c9e-bfbe-5eba9c2d6ecc">

3. Clicking Done

What might we need to replicate the issue?
Login to
https://www.parkinsonseurope.org/umbraco_epda_cms_admin/

Using login details
Duncan
epdaEP123@

Go to form https://www.parkinsonseurope.org/umbraco_epda_cms_admin/#/forms/form/entries/a008ad7a-7c3f-41a0-b017-07fbc0b13a3a

Are there any errors reported in the logs or browser console?
No errors
